$Env:DOTFILES="D:\code\dotfiles"
$Env:THEME="catppuccin"
$Env:KOMOREBI_CONFIG_HOME="$Env:DOTFILES\komorebi\$Env:THEME"
$Env:WHKD_CONFIG_HOME="$Env:DOTFILES\komorebi\whkd"
$Env:YASB_CONFIG_HOME="$Env:DOTFILES\yasb\$Env:THEME"
$Env:XDG_CONFIG_HOME="$HOME\.config"
