fork = false
frame = "none"
idle = true
icon = "D:/code/dotfiles/neovide/neovide.ico"
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
opengl = false                                # macOS/Windows only
srgb = true                                   # platform-specific: false (Linux/macOS) or true (Windows)
tabs = false
vsync = true
wsl = false

[font]
normal = [
  'DankMono Nerd Font',
] # Will use the bundled Fira Code Nerd Font by default
size = 13.0
hinting = "full"
edging = "antialias"

[box-drawing]
# "font-glyph", "native" (default) or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4] # Thin and thick values respectively, for all sizes
